apiVersion: v1
kind: Service
metadata:
  name: fortress-llm
spec:
  selector:
    app: fortress-llm
  ports:
    - name: ollama
      protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
