apiVersion: v1
kind: Service
metadata:
  name: fortress-frontend
spec:
  selector:
    app: fortress-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
